import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import favicon_light from '../public/favicon_light.png';
import favicon_dark from '../public/favicon_dark.png';


const inter = Inter({ 
  weight: ['100', '300', '400', '500', '600', '700'],
  subsets: ['latin'] 
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: [{rel: 'icon', url: '/favicon_light.png', type: 'image/png', media: '(prefers-color-scheme: light)'}, {rel: 'icon', url: '/favicon_dark.png', type: 'image/png', media: '(prefers-color-scheme: dark)'}]
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
